{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "axlr.name" . }}
  labels:
    {{- include "axlr.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: axlr
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.ingressFrom | nindent 8 }}
      ports:
        - {protocol: TCP, port: 8443}
        {{- if .Values.grpc.enabled }}
        - {protocol: TCP, port: 9443}
        {{- end }}
  egress:
    - to:
        {{- toYaml .Values.networkPolicy.egressTo | nindent 8 }}
{{- end }}
