apiVersion: v1
kind: Service
metadata:
  name: {{ include "axlr.name" . }}
  labels:
    {{- include "axlr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: axlr
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: https
    {{- if .Values.grpc.enabled }}
    - name: grpc
      port: {{ .Values.grpc.port }}
      targetPort: grpc
    {{- end }}
